schema_version: 1

context:
  version: "0.10.3"

package:
  name: htmy
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/h/htmy/htmy-${{ version }}.tar.gz
    sha256: 2178c4d5142948225c9a2129766375fda3fd26242b074f63912ae40d1a697824

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - anyio >=4.7.0,<5
    - async-lru >=2.0.5,<3
    - markdown >=3.8,<4

tests:
  - python:
      imports:
        - htmy
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/volfpeter/htmy
  summary: Async, pure-Python server-side rendering engine.

extra:
  recipe-maintainers:
    - davidbrochart
